name: qbbr.io
pygments: true
description: personal blog about linux (debian), hacking and programming
keywords: blog, linux, debian, hacking, programming
tag_page_layout: tag_page
tag_page_dir: blog/tag
permalink: /:categories/:title.html
timezone: UTC

exclude: [README.md, LICENSE]

google_analytics:
  enabled: true
  track_id: UA-42421652-1
