on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    name: Build and Deploy my static site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build
      run: ./build
    - name: Deploy to qbbr.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: qbbr/qbbr.github.io
        publish_branch: master
        publish_dir: ./output

